version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 0000
      
  api:
    image: "node:latest"
    volumes:
      - ./:/usr/src/app
    expose:
      - "8080"
    command: "npm start"

  myreact:
    image: "node:latest"
    volumes:
      - ./:/usr/src/app
    expose:
      - "8080"
    command: "npm start"